# Generated by Django 3.2 on 2022-11-02 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_auto_20221101_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 11, 2, 11, 56, 2, 387889, tzinfo=utc)),
        ),
    ]
