# Generated by Django 3.2 on 2022-11-04 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_auto_20221102_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 4, 14, 944272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 11, 4, 11, 4, 14, 943271, tzinfo=utc)),
        ),
    ]
